name: Matrix Demo
on:
    push:
        branches: 
            - main
jobs:
    build:
        strategy:
            matrix: #Matrix feature allows you to run the same job with different configurations
                node-version: [14, 16, 18]
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{matrix.os}}
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: ${{matrix.node-version}} 
            - name: Install dependencies
              uses: npm ci
            - name: Build project
              run: npm run build               
